[package]
name = "filecoin-webapi"
version = "0.1.0"
authors = ["石博文 <sbw@sbw.so>"]
edition = "2018"

[dependencies]
actix-web = "^2"
log = "*"
env_logger = "*"
actix-rt = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
json = "*"

[dependencies.filecoin-proofs-api]
git = "https://github.com/filecoin-project/rust-filecoin-proofs-api.git"
branch = "master"